### ISSUE TITLE
Only works with CMSIS V1 in STM32CubeMX

### ISSUE THREAD

**Issue by mhai97** [mincrmatt12/stm32cube-platformio-freertos#3]
If anyone cannot build project, remember to change CMSIS V2 in STM32CubeMX to V1.

**Comment by mincrmatt12** [comment]
Yeah, this repo doesn't currently have the cmsis-rtos v2 headers yet.

**Comment by mincrmatt12** [comment]
The new version I've just published to the registry should fix this if you set the configuration option `custom_freertos_cmsis_impl` to `CMSIS_RTOS_V2`.

**Comment by mhai97** [comment]
Wow that's just so quick. Thanks
