### ISSUE TITLE
Re-use the code inside .platformio/packages/ ?

### ISSUE THREAD

**Issue by jcw** [mincrmatt12/stm32cube-platformio-freertos#6]
Thanks for sharing this. It looks like this will work out of the box for F767ZI as well. Splendid!

Have you considered tying into the FreeRTOS sources which are inside the PlatformIO package area? See: `.platformio/packages/framework-stm32cubef7/Middlewares/Third_Party/FreeRTOS`. It'd avoid having to maintain a separate copy of FreeRTOS yourself.

FWIW, I tried using a symlink in `lib/FreeRTOS` as follows, but that doesn't work (maybe PIO doesn't follow symlinks):

    -> ../../../../.platformio/packages/framework-stm32cubef7/Middlewares/Third_Party/FreeRTOS/Source

**Update** - same comment w.r.t. your LwIP repository - I happen to be using both and am looking for a way to reduce code duplication and dependencies (to prevent potential long-term breakage).

**Comment by mincrmatt12** [comment]
When I first made this, the cube package in PlatformIO didn't have the third-party middlewares included, but that appears to have changed (I don't really use this much anymore, now I mostly just use some CMake-incantations for my projects)

Briefly looking at the current state of the platformio stm32 platform, you'll probably have better luck just asking for them to add support for the FreeRTOS and LwIP middlewares there directly if you want to go this route, as there isn't (afaik) a good way to include arbitrary extra files in a platformio library.

**Comment by jcw** [comment]
Ok, thanks.
