### ISSUE TITLE
How to set custom_freertos_config_location？

### ISSUE THREAD

**Issue by ghost** [mincrmatt12/stm32cube-platformio-freertos#8]
I tried to increase the custom_freertos_config_location setting on platformIO, but it doesn’t seem to work. I still can’t find FreeRTOSConfig.h. Can you give me an example of platformio.ini setting?

**Comment by mincrmatt12** [comment]
There should be a working example [here](https://github.com/mincrmatt12/stm32cube-platformio-lib-generators/tree/master/examples/test-rtos)

**Comment by ghost** [comment]
Thank you very much, you helped me solve the problem very well
